/** Demo content is used until a Supabase project is configured. */
export const articles = [
  {id:1,slug:'regional-trade-corridors-open-new-opportunities',title:'Regional trade corridors open new opportunities for local businesses',excerpt:'Businesses across the region are preparing for a new chapter of easier cross-border trade and shared growth.',category:'Business',author:'Adwoa Mensah',date:'August 1, 2026',time:'2 hours ago',views:12840,reading:5,image:'https://images.unsplash.com/photo-1565514020179-026b92b2d52f?auto=format&fit=crop&w=1200&q=82',featured:true},
  {id:2,slug:'parliament-approves-community-health-plan',title:'Parliament approves landmark community health plan',excerpt:'The new policy expands primary care access and equips district clinics with essential resources.',category:'Politics',author:'Kwame Agyeman',date:'August 1, 2026',time:'3 hours ago',views:9650,reading:4,image:'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1000&q=82',featured:true},
  {id:3,slug:'young-builders-shaping-africas-digital-future',title:'Young builders are shaping Africa’s digital future',excerpt:'A growing generation of founders is turning local challenges into scalable, useful technology.',category:'Technology',author:'Nana Osei',date:'August 1, 2026',time:'4 hours ago',views:7450,reading:6,image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=82',featured:true},
  {id:4,slug:'black-stars-ready-for-qualifier',title:'Black Stars ready for decisive qualifier this weekend',excerpt:'The national side says preparation has been focused, composed and full of belief.',category:'Sports',author:'Esi Kwarteng',date:'July 31, 2026',time:'Yesterday',views:21050,reading:3,image:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1000&q=82',featured:true},
  {id:5,slug:'schools-embrace-practical-learning',title:'Schools embrace practical learning as term begins',excerpt:'Teachers and families are welcoming a renewed focus on skills for a changing world.',category:'Education',author:'Akosua Owusu',date:'July 31, 2026',time:'Yesterday',views:6320,reading:4,image:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=82'},
  {id:6,slug:'creative-economy-takes-centre-stage',title:'Creative economy takes centre stage at city festival',excerpt:'Artists, filmmakers and designers are bringing a confident new energy to the capital.',category:'Entertainment',author:'Ama Serwaa',date:'July 30, 2026',time:'2 days ago',views:9100,reading:4,image:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=82'},
  {id:7,slug:'climate-finance-for-coastal-cities',title:'Climate finance aims to protect coastal cities',excerpt:'Mayors call for targeted adaptation funding to keep coastal communities resilient.',category:'Africa',author:'Daniel Boadi',date:'July 30, 2026',time:'2 days ago',views:10800,reading:5,image:'https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1000&q=82'},
  {id:8,slug:'global-markets-see-cautious-optimism',title:'Global markets see cautious optimism after mixed week',excerpt:'Analysts say investors are watching inflation data and central bank signals closely.',category:'World',author:'Joseph Aidoo',date:'July 29, 2026',time:'3 days ago',views:5840,reading:4,image:'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1000&q=82'},
  {id:9,slug:'new-farming-models-help-communities-thrive',title:'New farming models help communities thrive',excerpt:'Farmers are combining local knowledge with climate-smart approaches for better harvests.',category:'Health',author:'Efua Armah',date:'July 29, 2026',time:'3 days ago',views:7030,reading:5,image:'https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1000&q=82'},
  {id:10,slug:'editorial-why-trust-is-our-common-currency',title:'Why trust is our common currency',excerpt:'In a fast-moving media age, facts and care remain our most important public service.',category:'Opinion',author:'The Editorial Board',date:'July 28, 2026',time:'4 days ago',views:11220,reading:4,image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1000&q=82'},
  {id:11,slug:'city-rail-project-enters-new-phase',title:'City rail project enters a promising new phase',excerpt:'Commuters will see new stations open after the next stage of construction concludes.',category:'Business',author:'Kofi Anane',date:'July 28, 2026',time:'4 days ago',views:8790,reading:3,image:'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=1000&q=82'},
  {id:12,slug:'athletes-inspire-at-youth-games',title:'Athletes inspire at youth games opening ceremony',excerpt:'A vibrant gathering of talent and teamwork opens the annual competition.',category:'Sports',author:'Esi Kwarteng',date:'July 27, 2026',time:'5 days ago',views:13800,reading:3,image:'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1000&q=82'}
];
export const categories = [
  ['Ghana','fa-flag'],['Politics','fa-landmark'],['Business','fa-chart-line'],['Technology','fa-microchip'],['Entertainment','fa-film'],['Sports','fa-futbol'],['Health','fa-heart-pulse'],['Education','fa-graduation-cap'],['Africa','fa-earth-africa'],['World','fa-globe'],['Opinion','fa-pen-nib']
];
export const videos = [
  {title:'Inside the innovation hubs changing how Africa builds',image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=82'},
  {title:'The evening briefing: five stories you need to know',image:'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=900&q=82'},
  {title:'In pictures: a weekend of sport and community',image:'https://images.unsplash.com/photo-1518604666860-9ed391f76460?auto=format&fit=crop&w=900&q=82'}
];
export const gallery = [
  {title:'A city in motion',image:'https://images.unsplash.com/photo-1536697246787-1f7ae568d89a?auto=format&fit=crop&w=1000&q=82'},
  {title:'Craft and colour',image:'assets/gallery-craft.svg'},
  {title:'The energy of game day',image:'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=82'},
  {title:'A brighter start',image:'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=82'},
  {title:'Built for tomorrow',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=82'}
];
