import { toast } from './components.js';

const $=(selector,parent=document)=>parent.querySelector(selector);
const esc=(value='')=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const apiRoot=()=>String(window.LK_AGGREGATOR_API_URL||location.origin).replace(/\/$/,'');
const money=(amount,currency='GHS')=>new Intl.NumberFormat('en-GH',{style:'currency',currency}).format(Number(amount||0));
async function request(path,options={}){const response=await fetch(`${apiRoot()}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'The request could not be completed.');return payload;}
const benefits=value=>Array.isArray(value)&&value.length?`<ul>${value.map(item=>`<li><i class="fa-solid fa-check"></i> ${esc(item)}</li>`).join('')}</ul>`:'';
export async function mountAdvertiseMarketplace(){
  const title=$('#static-title'),subtitle=$('#static-subtitle'),target=$('#static-content');if(!target)return;
  title.textContent='Advertise with LK Newsroom';subtitle.textContent='Connect your organisation with an informed audience through clear, measurable, brand-safe campaigns.';
  target.innerHTML='<div class="spinner"></div>';
  try{
    const {packages=[]}=await request('/v1/monetization/packages');
    target.innerHTML=`<section class="marketplace-intro"><span class="eyebrow">Commercial partnerships</span><h2>Build a campaign around your goal.</h2><p>Choose a package below or send your brief. Every campaign is clearly labelled, mobile-ready and measured for reach and engagement.</p></section><div class="package-grid">${packages.map(item=>`<article class="pricing-card"><span class="eyebrow">${esc(item.placement.replace(/-/g,' '))}</span><h3>${esc(item.title)}</h3><p>${esc(item.description||'A flexible LK Newsroom campaign.')}</p><strong class="pricing-card__price">${money(item.price,item.currency)}</strong><span class="meta">${Number(item.duration_days)} days</span>${benefits(item.features)}<button class="btn btn-primary select-package" data-id="${item.id}" data-title="${esc(item.title)}">Choose this package</button></article>`).join('')||'<p class="text-muted">Advertising packages are being updated. Send us a brief below.</p>'}</div><section class="advertiser-form-wrap"><div><span class="eyebrow">Start a conversation</span><h2>Tell us about your campaign</h2><p>We will reply with availability, pricing and creative guidance.</p></div><form id="advertiser-request-form" class="form-card"><input type="hidden" name="packageId"><div class="form-group"><label>Company name</label><input class="form-control" name="companyName" required maxlength="160"></div><div class="form-group"><label>Your name</label><input class="form-control" name="contactName" maxlength="100"></div><div class="form-group"><label>Email address</label><input class="form-control" type="email" name="email" required></div><div class="form-group"><label>Phone</label><input class="form-control" name="phone" maxlength="60"></div><div class="form-group"><label>Website</label><input class="form-control" type="url" name="website" placeholder="https://"></div><div class="form-group"><label>Campaign type</label><select class="form-control" name="advertisementType"><option value="display">Display advertising</option><option value="sponsored">Sponsored article</option><option value="video">Video partnership</option><option value="newsletter">Newsletter partnership</option></select></div><div class="form-group"><label>Estimated budget</label><input class="form-control" type="number" min="0" step="0.01" name="budget"></div><div class="form-group"><label>Campaign duration (days)</label><input class="form-control" type="number" min="1" max="366" name="durationDays" value="30"></div><div class="form-group"><label>What do you want to achieve?</label><textarea class="form-control" rows="4" name="message" maxlength="3000" placeholder="Audience, dates, placement or creative notes"></textarea></div><button class="btn btn-primary" type="submit">Send advertising request <i class="fa-solid fa-arrow-right"></i></button></form></section>`;
    document.querySelectorAll('.select-package').forEach(button=>button.addEventListener('click',()=>{const form=$('#advertiser-request-form');form.elements.packageId.value=button.dataset.id;form.elements.message.value=`Interested in the ${button.dataset.title} package.\n\n${form.elements.message.value}`.trim();form.scrollIntoView({behavior:'smooth',block:'center'});form.elements.companyName.focus();}));
    $('#advertiser-request-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,fields=form.elements;const payload=Object.fromEntries(new FormData(form));try{await request('/v1/monetization/advertiser-requests',{method:'POST',body:JSON.stringify(payload)});form.reset();toast('Thanks — your advertising request has been sent.');}catch(error){toast(error.message);}});
  }catch(error){target.innerHTML=`<div class="empty-state"><i class="fa-solid fa-triangle-exclamation fa-2x"></i><p>${esc(error.message)}</p></div>`;}
}
async function checkPayment(){const reference=new URLSearchParams(location.search).get('payment');if(!reference)return '';try{const payload=await request(`/v1/monetization/payments/${encodeURIComponent(reference)}`);const item=payload.data;const status=item.status==='paid'?'Thank you — your payment has been confirmed.':item.status==='initiated'?'Your payment is awaiting confirmation. You may return here shortly.':'Your payment is still being processed.';return `<div class="payment-status"><strong>${esc(status)}</strong><span>Reference: ${esc(item.reference)}</span></div>`;}catch{return '<div class="payment-status">Your payment return was received. Please check your email or contact LK Newsroom if you need help.</div>';}}
export async function mountSupportPage(){
  const title=$('#static-title'),subtitle=$('#static-subtitle'),target=$('#static-content');if(!target)return;
  title.textContent='Support LK Newsroom';subtitle.textContent='Help sustain independent reporting, or become a premium reader for an ad-free experience and special access.';target.innerHTML='<div class="spinner"></div>';
  try{const [{plans=[]},paymentStatus]=await Promise.all([request('/v1/monetization/packages'),checkPayment()]);target.innerHTML=`${paymentStatus}<section class="marketplace-intro"><span class="eyebrow">Reader-powered journalism</span><h2>Support reporting that matters.</h2><p>Your membership and one-off support help keep LK Newsroom accessible, independent and focused on the public interest.</p></section><div class="package-grid membership-grid">${plans.map(plan=>`<article class="pricing-card"><span class="eyebrow">${esc(plan.interval)} membership</span><h3>${esc(plan.name)}</h3><p>${esc(plan.description||'Reader benefits and independent journalism.')}</p><strong class="pricing-card__price">${money(plan.amount,plan.currency)}</strong><span class="meta">per ${esc(plan.interval==='yearly'?'year':'month')}</span>${benefits(plan.features)}<button class="btn btn-primary buy-plan" data-id="${plan.id}" data-amount="${plan.amount}" data-currency="${plan.currency}">Become a member</button></article>`).join('')}</div><section class="support-form-wrap"><div><span class="eyebrow">One-time donation</span><h2>Make a contribution</h2><p>Choose any amount. Your support is received securely through the payment provider you select.</p></div><form id="donation-form" class="form-card"><div class="form-group"><label>Name (optional)</label><input class="form-control" name="name" maxlength="120"></div><div class="form-group"><label>Email address</label><input class="form-control" type="email" name="email" required></div><div class="form-group"><label>Amount</label><input class="form-control" type="number" name="amount" min="1" step="0.01" value="20" required></div><div class="form-group"><label>Currency</label><select class="form-control" name="currency"><option value="GHS">GHS</option><option value="USD">USD</option><option value="GBP">GBP</option><option value="EUR">EUR</option></select></div><div class="form-group"><label>Payment provider</label><select class="form-control" name="provider"><option value="paystack">Paystack</option><option value="stripe">Stripe</option></select></div><div class="form-group"><label>Message (optional)</label><textarea class="form-control" name="message" rows="3" maxlength="500"></textarea></div><button class="btn btn-primary" type="submit">Continue securely <i class="fa-solid fa-lock"></i></button></form></section>`;
    const checkout=async payload=>{try{const result=await request('/v1/monetization/checkout',{method:'POST',body:JSON.stringify(payload)});location.assign(result.checkoutUrl);}catch(error){toast(error.message);}};
    document.querySelectorAll('.buy-plan').forEach(button=>button.addEventListener('click',()=>{const email=prompt('Enter your email address for this membership:');if(!email)return;const provider=prompt('Type paystack or stripe','paystack');if(!provider)return;checkout({kind:'subscription',planId:button.dataset.id,email,provider,currency:button.dataset.currency});}));
    $('#donation-form').addEventListener('submit',event=>{event.preventDefault();const fields=event.currentTarget.elements;checkout({kind:'donation',name:fields.name.value,email:fields.email.value,amount:Number(fields.amount.value),currency:fields.currency.value,provider:fields.provider.value,message:fields.message.value});});
  }catch(error){target.innerHTML=`<div class="empty-state"><i class="fa-solid fa-triangle-exclamation fa-2x"></i><p>${esc(error.message)}</p></div>`;}
}
