import { supabase } from './supabase-client.js';
import { toast } from './components.js';

const $=(selector,parent=document)=>parent.querySelector(selector);
const esc=(value='')=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const money=(amount,currency='GHS')=>new Intl.NumberFormat('en-GH',{style:'currency',currency}).format(Number(amount||0));
const date=value=>value?new Date(value).toLocaleString():'—';
const apiRoot=()=>window.LK_AGGREGATOR_API_URL||location.origin;
async function data(result){if(result.error)throw result.error;return result.data||[];}
async function adminRequest(path,options={}){const {data:session}=await supabase.auth.getSession();const response=await fetch(`${apiRoot()}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.session?.access_token||''}`,...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed.');return payload;}
const rows=(items,render,empty,colspan=1)=>items.length?items.map(render).join(''):`<tr><td colspan="${colspan}" class="text-muted">${empty}</td></tr>`;
const featureList=value=>Array.isArray(value)?value.map(item=>`<li>${esc(item)}</li>`).join(''):'';
function packageForm(item={}){return `<section class="panel"><div class="section-heading"><div><h3>Advertising packages</h3><p class="text-muted">Set the public packages companies can choose when they advertise with LK Newsroom.</p></div></div><form id="package-form" class="editor-grid"><input type="hidden" name="id" value="${esc(item.id||'')}"><div><div class="form-group"><label>Package name</label><input class="form-control" name="title" required value="${esc(item.title||'')}"></div><div class="form-group"><label>Slug</label><input class="form-control" name="slug" required value="${esc(item.slug||'')}"></div><div class="form-group"><label>Placement</label><select class="form-control" name="placement">${['homepage-top','homepage-hero','homepage-sidebar','article-inline','article-sidebar','footer-banner','sticky-bottom','sponsored-news'].map(option=>`<option ${item.placement===option?'selected':''}>${option}</option>`).join('')}</select></div><div class="form-group"><label>Duration (days)</label><input class="form-control" name="durationDays" type="number" min="1" max="366" value="${Number(item.duration_days||30)}"></div></div><div><div class="form-group"><label>Price</label><input class="form-control" name="price" type="number" min="0" step="0.01" value="${esc(item.price||0)}"></div><div class="form-group"><label>Currency</label><select class="form-control" name="currency">${['GHS','USD','GBP','EUR','NGN','ZAR'].map(option=>`<option ${item.currency===option?'selected':''}>${option}</option>`).join('')}</select></div><div class="form-group"><label>Description</label><textarea class="form-control" name="description" rows="2">${esc(item.description||'')}</textarea></div><div class="form-group"><label>Features (one per line)</label><textarea class="form-control" name="features" rows="3">${esc((item.features||[]).join('\n'))}</textarea></div><label><input name="active" type="checkbox" ${item.active!==false?'checked':''}> Show publicly</label><button class="btn btn-primary" type="submit" style="margin:14px 0 0 12px">Save package</button></div></form></section>`;}
function requestTable(items){return `<section class="panel"><div class="section-heading"><div><h3>Advertiser requests</h3><p class="text-muted">Approve, quote or decline new company campaigns.</p></div><span class="meta">${items.filter(item=>item.status==='pending').length} pending</span></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Company</th><th>Request</th><th>Budget</th><th>Received</th><th>Status</th><th></th></tr></thead><tbody>${rows(items,item=>`<tr><td><strong>${esc(item.company_name)}</strong><br><span class="meta">${esc(item.contact_name||item.email)}</span></td><td>${esc(item.advertisement_type)}<br><span class="meta">${esc(item.advertising_packages?.title||item.requested_placement||'Custom campaign')}</span></td><td>${item.budget?money(item.budget,item.currency):'Not stated'}</td><td>${date(item.created_at)}</td><td><select class="form-control request-status" data-id="${item.id}">${['pending','quoted','approved','rejected','converted'].map(status=>`<option value="${status}" ${item.status===status?'selected':''}>${status}</option>`).join('')}</select></td><td><button class="btn btn-outline quote-request" data-id="${item.id}">Review</button></td></tr>`, 'No advertiser requests yet.',6)}</tbody></table></div></section>`;}
function sponsorForm(articles,details){return `<section class="panel"><h3>Sponsored news</h3><p class="text-muted">Link a published article to its sponsor. The story remains clearly labelled wherever it appears.</p><form id="sponsor-form" class="compact-form"><select class="form-control" name="articleId" required><option value="">Choose published article</option>${articles.map(article=>`<option value="${article.id}">${esc(article.title)}</option>`).join('')}</select><input class="form-control" name="sponsorName" required placeholder="Sponsor name"><input class="form-control" name="sponsorUrl" type="url" placeholder="Sponsor website (https://…)"><input class="form-control" name="paidAmount" type="number" min="0" step="0.01" placeholder="Campaign value"><button class="btn btn-primary" type="submit">Save sponsor</button></form><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Article</th><th>Sponsor</th><th>Views</th><th>Campaign value</th></tr></thead><tbody>${rows(details,item=>`<tr><td><strong>${esc(item.articles?.title||'Deleted article')}</strong></td><td>${esc(item.sponsor_name)}</td><td>${Number(item.articles?.view_count||0).toLocaleString()}</td><td>${item.paid_amount?money(item.paid_amount,item.currency):'—'}</td></tr>`,'No sponsored stories yet.',4)}</tbody></table></div></section>`;}
function affiliatePanel(campaigns,links){return `<section class="panel"><h3>Affiliate marketing</h3><form id="affiliate-campaign-form" class="compact-form"><input class="form-control" name="name" required placeholder="Campaign name"><input class="form-control" name="advertiser" placeholder="Partner / advertiser"><input class="form-control" name="commission" type="number" min="0" max="100" step="0.01" placeholder="Default commission %"><button class="btn btn-outline" type="submit">Add campaign</button></form><form id="affiliate-link-form" class="compact-form" style="margin-top:12px"><select class="form-control" name="campaignId"><option value="">No campaign</option>${campaigns.map(item=>`<option value="${item.id}">${esc(item.name)}</option>`).join('')}</select><input class="form-control" name="title" required placeholder="Product or offer"><input class="form-control" name="url" type="url" required placeholder="Destination URL"><input class="form-control" name="code" required placeholder="Tracking code"><button class="btn btn-primary" type="submit">Add affiliate link</button></form><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Offer</th><th>Campaign</th><th>Tracking URL</th><th>Commission</th><th>Status</th></tr></thead><tbody>${rows(links,item=>`<tr><td><strong>${esc(item.title)}</strong></td><td>${esc(item.affiliate_campaigns?.name||'—')}</td><td><a class="text-link" target="_blank" rel="noopener" href="/go/affiliate/${encodeURIComponent(item.tracking_code)}">/go/affiliate/${esc(item.tracking_code)}</a></td><td>${item.commission_rate?`${item.commission_rate}%`:'—'}</td><td>${item.active?'Active':'Paused'}</td></tr>`,'No affiliate links yet.',5)}</tbody></table></div></section>`;}
function membershipsPanel(plans,subscriptions,donations){return `<section class="panel"><h3>Reader membership and support</h3><form id="membership-form" class="compact-form"><input class="form-control" name="name" required placeholder="Plan name"><input class="form-control" name="slug" required placeholder="plan-slug"><input class="form-control" name="amount" type="number" min="0" step="0.01" required placeholder="Price"><select class="form-control" name="interval"><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="one_time">One time</option></select><button class="btn btn-primary" type="submit">Add plan</button></form><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Plan</th><th>Price</th><th>Active subscribers</th><th>Donations received</th></tr></thead><tbody>${rows(plans,item=>`<tr><td><strong>${esc(item.name)}</strong><br><span class="meta">${esc(item.description||'Premium access')}</span></td><td>${money(item.amount,item.currency)} / ${esc(item.interval)}</td><td>${subscriptions.filter(row=>row.plan_id===item.id&&row.status==='active').length}</td><td>${money(donations.filter(row=>row.status==='paid').reduce((sum,row)=>sum+Number(row.amount||0),0),'GHS')}</td></tr>`,'No membership plans yet.',4)}</tbody></table></div><p class="form-help">For live transactions set <code>PAYSTACK_SECRET_KEY</code> or <code>STRIPE_SECRET_KEY</code> in Railway. Do not paste payment secrets in this dashboard.</p></section>`;}
function paymentTable(transactions){return `<section class="panel"><h3>Payment activity</h3><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Type</th><th>Amount</th><th>Provider</th><th>Status</th><th>Created</th></tr></thead><tbody>${rows(transactions,item=>`<tr><td><code>${esc(item.reference)}</code></td><td>${esc(item.kind)}</td><td>${money(item.amount,item.currency)}</td><td>${esc(item.provider)}</td><td>${esc(item.status)}</td><td>${date(item.created_at)}</td></tr>`,'No payment activity yet.',6)}</tbody></table></div></section>`;}
async function loadPublishedArticles(){return data(await supabase.from('articles').select('id,title').eq('status','published').order('published_at',{ascending:false}).limit(250));}
export async function mountMonetizationSuite(){
  const view=$('#admin-view');if(!view||!supabase)return;
  view.innerHTML='<section class="panel"><p class="text-muted">Loading monetization tools…</p></section>';
  try{
    const [overview,articles]=await Promise.all([adminRequest('/v1/admin/monetization/overview'),loadPublishedArticles()]);
    view.innerHTML=`<div class="monetization-suite">${packageForm()}${requestTable(overview.requests)}${sponsorForm(articles,overview.sponsored)}${affiliatePanel(overview.affiliateCampaigns,overview.affiliateLinks)}${membershipsPanel(overview.plans,overview.subscriptions,overview.donations)}${paymentTable(overview.transactions)}</div>`;
    bindSuite(overview,articles);
  }catch(error){view.innerHTML=`<section class="panel"><h3>Monetization setup required</h3><p class="text-muted">${esc(error.message||'Run the monetization suite SQL migration first.')}</p><p class="form-help">Run <code>supabase/monetization-suite-upgrade.sql</code> in the Supabase SQL Editor, then refresh this page.</p></section>`;}
}
function bindSuite(overview,articles){
  $('#package-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const values=form.elements;const payload={title:values.title.value.trim(),slug:values.slug.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'-'),placement:values.placement.value,duration_days:Number(values.durationDays.value),price:Number(values.price.value),currency:values.currency.value,description:values.description.value.trim()||null,features:values.features.value.split('\n').map(item=>item.trim()).filter(Boolean),active:values.active.checked};try{await data(await supabase.from('advertising_packages').insert(payload));toast('Advertising package saved.');mountMonetizationSuite();}catch(error){toast(error.message||'Could not save package.');}});
  document.querySelectorAll('.quote-request').forEach(button=>button.addEventListener('click',async()=>{const item=overview.requests.find(row=>row.id===button.dataset.id);if(!item)return;const status=prompt('Status: pending, quoted, approved, rejected, or converted',item.status);if(!status)return;const quotedPrice=prompt('Quoted price (leave blank if not needed)',item.quoted_price??'');const adminNotes=prompt('Admin note for this request',item.admin_notes||'');try{await adminRequest(`/v1/admin/monetization/requests/${item.id}`,{method:'PATCH',body:JSON.stringify({status,quotedPrice,adminNotes})});toast('Advertiser request updated.');mountMonetizationSuite();}catch(error){toast(error.message);}}));
  $('#sponsor-form')?.addEventListener('submit',async event=>{event.preventDefault();const values=event.currentTarget.elements;try{await data(await supabase.from('sponsored_article_details').upsert({article_id:values.articleId.value,sponsor_name:values.sponsorName.value.trim(),sponsor_url:values.sponsorUrl.value.trim()||null,paid_amount:values.paidAmount.value?Number(values.paidAmount.value):null},{onConflict:'article_id'}));toast('Sponsored story details saved.');mountMonetizationSuite();}catch(error){toast(error.message||'Could not save sponsor.');}});
  $('#affiliate-campaign-form')?.addEventListener('submit',async event=>{event.preventDefault();const values=event.currentTarget.elements;try{await data(await supabase.from('affiliate_campaigns').insert({name:values.name.value.trim(),advertiser_name:values.advertiser.value.trim()||null,default_commission_rate:values.commission.value?Number(values.commission.value):null}));toast('Affiliate campaign saved.');mountMonetizationSuite();}catch(error){toast(error.message||'Could not save campaign.');}});
  $('#affiliate-link-form')?.addEventListener('submit',async event=>{event.preventDefault();const values=event.currentTarget.elements;try{await data(await supabase.from('affiliate_links').insert({campaign_id:values.campaignId.value||null,title:values.title.value.trim(),destination_url:values.url.value.trim(),tracking_code:values.code.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'-')}));toast('Affiliate link saved.');mountMonetizationSuite();}catch(error){toast(error.message||'Could not save affiliate link.');}});
  $('#membership-form')?.addEventListener('submit',async event=>{event.preventDefault();const values=event.currentTarget.elements;try{await data(await supabase.from('membership_plans').insert({name:values.name.value.trim(),slug:values.slug.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'-'),amount:Number(values.amount.value),interval:values.interval.value,currency:'GHS'}));toast('Membership plan saved.');mountMonetizationSuite();}catch(error){toast(error.message||'Could not save membership plan.');}});
}
