import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const url=window.LK_SUPABASE_URL, key=window.LK_SUPABASE_ANON_KEY;
export const configured=Boolean(url&&key&&!url.includes('YOUR_PROJECT'));
export const supabase=configured?createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
export const newsApi={
  async published({category,limit=12,from=0}={}) {if(!supabase)return[];let q=supabase.from('articles').select('*, categories(name, slug), news_sources(name,slug), authors(name)').eq('status','published').is('duplicate_of',null).lte('published_at',new Date().toISOString()).order('published_at',{ascending:false}).range(from,from+limit-1);if(category)q=q.eq('categories.slug',category);const {data,error}=await q;if(error)throw error;return data;},
  async advertisements(limit=5){if(!supabase)return[];const {data,error}=await supabase.from('advertisements').select('id,name,image_url,target_url,html_content,placement').eq('active',true).order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[];},
  async trackAdvertisement(id,event){if(!supabase||!id)return;const fn=event==='click'?'record_ad_click':'record_ad_impression';const {error}=await supabase.rpc(fn,{ad_uuid:id});if(error)throw error;},
  async article(identifier){if(!supabase)throw new Error('Supabase is not configured.');const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(identifier);let articleQuery=supabase.from('articles').select('*, categories(name,slug), news_sources(name,slug), authors(name), article_tags(tags(name,slug))').eq('status','published').is('duplicate_of',null);articleQuery=uuid?articleQuery.eq('id',identifier):articleQuery.eq('slug',identifier);const {data:article,error}=await articleQuery.maybeSingle();if(error)throw error;if(!article)throw new Error('This article is no longer available.');const [related,moreFromSource,previous,next,galleryRows,videoRows,commentRows]=await Promise.all([supabase.from('articles').select('*,categories(name,slug),news_sources(name,slug),authors(name)').eq('status','published').eq('category_id',article.category_id).neq('id',article.id).is('duplicate_of',null).order('published_at',{ascending:false}).limit(6),article.source_id?supabase.from('articles').select('*,categories(name,slug),news_sources(name,slug),authors(name)').eq('status','published').eq('source_id',article.source_id).neq('id',article.id).is('duplicate_of',null).order('published_at',{ascending:false}).limit(5):Promise.resolve({data:[]}),supabase.from('articles').select('*,categories(name,slug),news_sources(name,slug),authors(name)').eq('status','published').lt('published_at',article.published_at).is('duplicate_of',null).order('published_at',{ascending:false}).limit(1),supabase.from('articles').select('*,categories(name,slug),news_sources(name,slug),authors(name)').eq('status','published').gt('published_at',article.published_at).is('duplicate_of',null).order('published_at',{ascending:true}).limit(1),supabase.from('gallery').select('id,title,caption,image_url,alt_text').eq('article_id',article.id).eq('status','published').order('sort_order').limit(12),supabase.from('videos').select('id,title,description,video_url,youtube_url,thumbnail_url,duration_seconds').eq('article_id',article.id).eq('status','published').order('published_at',{ascending:false}).limit(6),supabase.from('comments').select('id,display_name,body,created_at').eq('article_id',article.id).eq('status','approved').order('created_at',{ascending:false}).limit(50)]);return {data:article,related:related.data||[],moreFromSource:moreFromSource.data||[],previous:previous.data?.[0]||null,next:next.data?.[0]||null,gallery:galleryRows.data||[],videos:videoRows.data||[],comments:commentRows.data||[]};},
  async comment(articleId,displayName,body){if(!supabase)throw new Error('Supabase is not configured.');const {error}=await supabase.from('comments').insert({article_id:articleId,display_name:displayName,body,status:'pending'});if(error)throw error;},
  async incrementView(articleId) {if(!supabase)return;await supabase.rpc('increment_article_views',{article_uuid:articleId});},
  async upload(bucket,file,path) {if(!supabase)throw new Error('Supabase is not configured.');const {data,error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false,cacheControl:'3600'});if(error)throw error;return data;}
};
export async function subscribe(email){if(!supabase)return true;const {error}=await supabase.from('newsletter').insert({email});if(error && error.code!=='23505')throw error;return true;}
export async function subscribeRealtime(table,handler){if(!supabase)return null;return supabase.channel(`public:${table}`).on('postgres_changes',{event:'*',schema:'public',table},handler).subscribe();}
