import type { NewsProvider } from './types.js';
import { bbcProviders } from './bbc.js'; import { cnnProvider } from './cnn.js'; import { aljazeeraProvider } from './aljazeera.js'; import { reutersProvider } from './reuters.js';
import { ghanaProviders } from './ghana.js'; import { sportsProviders } from './sports.js'; import { technologyProviders } from './technology.js'; import { businessProviders } from './business.js'; import { nytProvider } from './nyt.js'; import { configuredRss, publisherRss } from './rss.js';
import { newsApiProvider, newsApiFootballProvider } from './newsapi.js';
import { fabrizioRomanoProvider } from './fabrizio.js';
import { videoProviders } from './youtube.js';

/** Source catalogue. RSS feeds are retrieved only where a publisher authorises them. API-only sources must receive a licensed endpoint through environment configuration. */
export const providers:NewsProvider[]=[...bbcProviders,cnnProvider,aljazeeraProvider,reutersProvider,...ghanaProviders,...sportsProviders,fabrizioRomanoProvider(),...technologyProviders,...businessProviders,nytProvider(),newsApiProvider(),newsApiFootballProvider(),...videoProviders,
 configuredRss('associated-press','Associated Press (AP)','AP_RSS_URL','United States','World'),configuredRss('sky-news','Sky News','SKY_NEWS_RSS_URL','United Kingdom','World'),configuredRss('france-24','France 24','FRANCE24_RSS_URL','France','World'),configuredRss('abc-news','ABC News','ABC_NEWS_RSS_URL','United States','World'),configuredRss('cbs-news','CBS News','CBS_NEWS_RSS_URL','United States','World'),configuredRss('nbc-news','NBC News','NBC_NEWS_RSS_URL','United States','World'),configuredRss('washington-post','The Washington Post','WASHINGTON_POST_RSS_URL','United States','World'),
 publisherRss('africanews','Africanews','AFRICANEWS_RSS_URL','https://www.africanews.com/feed/rss','Africa','Africa'),publisherRss('news24','News24','NEWS24_RSS_URL','https://feeds.24.com/articles/news24/topstories/rss','South Africa','Africa'),configuredRss('eastafrican','The EastAfrican','EASTAFRICAN_RSS_URL','East Africa','Africa'),configuredRss('citizen-tanzania','The Citizen Tanzania','CITIZEN_TZ_RSS_URL','Tanzania','Africa'),configuredRss('daily-nation','Daily Nation Kenya','DAILY_NATION_RSS_URL','Kenya','Africa'),
 configuredRss('billboard','Billboard','BILLBOARD_RSS_URL','United States','Entertainment'),configuredRss('variety','Variety','VARIETY_RSS_URL','United States','Entertainment'),configuredRss('hollywood-reporter','The Hollywood Reporter','HOLLYWOOD_REPORTER_RSS_URL','United States','Entertainment'),configuredRss('tmz','TMZ','TMZ_RSS_URL','United States','Entertainment'),configuredRss('pulse-ghana-entertainment','Pulse Ghana Entertainment','PULSE_GHANA_ENTERTAINMENT_RSS_URL','Ghana','Entertainment')
];
