import type { SupabaseClient } from '@supabase/supabase-js';
import { NewsAggregator } from '../services/newsAggregator.js';
export type WorkerTrigger='cron'|'manual'|'startup'|'vercel'|'railway'|'render'|'vps';
export interface WorkerResult {status:'completed'|'skipped'|'failed';runId?:string;startedAt:string;completedAt:string;fetched:number;added:number;updated:number;skipped:number;errors:number;results:unknown[];}
/** Long-running-safe worker entry point. A Supabase lease prevents overlapping schedules across deploy instances. */
export class NewsWorker {
  constructor(private db:SupabaseClient,private aggregator=new NewsAggregator(db)){}
  async run(trigger:WorkerTrigger='cron',source?:string):Promise<WorkerResult>{const startedAt=new Date().toISOString();const {data:locked,error:lockError}=await this.db.rpc('acquire_news_worker_lock',{p_lock_name:'news-aggregation',lease_seconds:270});if(lockError)throw lockError;if(!locked)return {status:'skipped',startedAt,completedAt:new Date().toISOString(),fetched:0,added:0,updated:0,skipped:0,errors:0,results:[]};const {data:run,error:runError}=await this.db.from('worker_runs').insert({trigger,status:'running',started_at:startedAt}).select('id').single();if(runError){await this.db.rpc('release_news_worker_lock',{p_lock_name:'news-aggregation'});throw runError;}try{const results=await this.aggregator.syncAll(source);const totals=results.reduce((sum,item:any)=>({fetched:sum.fetched+item.fetched,added:sum.added+item.inserted,updated:sum.updated+item.updated,skipped:sum.skipped+item.duplicates,errors:sum.errors+(item.status==='error'?1:0)}),{fetched:0,added:0,updated:0,skipped:0,errors:0});const completedAt=new Date().toISOString();await this.db.from('worker_runs').update({status:'completed',completed_at:completedAt,...totals,details:{results}}).eq('id',run.id);return {status:'completed',runId:run.id,startedAt,completedAt,...totals,results};}catch(error){const completedAt=new Date().toISOString();await this.db.from('worker_runs').update({status:'failed',completed_at:completedAt,error:error instanceof Error?error.message:String(error)}).eq('id',run.id);return {status:'failed',runId:run.id,startedAt,completedAt,fetched:0,added:0,updated:0,skipped:0,errors:1,results:[]};}finally{await this.db.rpc('release_news_worker_lock',{p_lock_name:'news-aggregation'});}}
}
